name: jupytext

on: [push]

jobs:
  do:
    runs-on: ubuntu-20.04
    env:
      TEMP_DIR: tmp_dir
      CONVERTED_PY_FILES: 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install jupytext
        pip install pylint
    - name: Convert committed .ipynb files to .py
      run: |
        echo $GITHUB_ENV
        mkdir ${{env.TEMP_DIR}}
        # git ls-files "*.ipynb" --with-tree=${{github.sha}}
        COMMITTED_IPYNBS=`git ls-files "*.ipynb" --with-tree=${{github.sha}}`
        # echo "${COMMITTED_IPYNBS}
        echo "${COMMITTED_IPYNBS}" | while read p; do
          echo ${p}
          PY_FILE=${{env.TEMP_DIR}}/${p//.ipynb/.py}
          echo Convert "${p}" to "${PY_FILE}"
          jupytext "${p}" -o "${PY_FILE}"
          echo "CONVERTED_PY_FILES=${{env.CONVERTED_PY_FILES}}${PY_FILE}" >> $GITHUB_ENV
        done
        ls -hltr
        ls -hltr ${{env.TEMP_DIR}}
        echo GITHUB_ENV: $GITHUB_ENV
    - name: ENV var test
      run: |
        echo ${{env.TEMP_DIR}}
        echo ${{env.CONVERTED_PY_FILES}}
