name: jupytext

on: [push]

jobs:
  do:
    runs-on: ubuntu-20.04
    env:
      TEMP_DIR: tmp_dir
      CONVERTED_PY_FILES: 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install jupytext
        pip install pylint
    - name: Convert committed .ipynb files to .py
      run: |
        echo $GITHUB_ENV
        mkdir ${{env.TEMP_DIR}}
        COMMITTED_IPYNBS=`git ls-files "*.ipynb" --with-tree=${{github.sha}}`
        while read -r p; do
          PY_FILE=${{env.TEMP_DIR}}/${p//.ipynb/.py}
          echo Convert "${p}" to "${PY_FILE}"
          jupytext "${p}" -o "${PY_FILE}"
          TMP_FILES="${TMP_FILES}${PY_FILE}"$'\n'
        done <<< "${COMMITTED_IPYNBS}"

        echo "CONVERTED_PY_FILES<<EOF" >> $GITHUB_ENV
        echo "${TMP_FILES}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Run pylint each converted .py files
      run: |
        while read -r p; do
          pylint ${p]
        done <<< "${{env.CONVERTED_PY_FILES}}"
      continue-on-error: true
