name: jupytext

on: [push]

jobs:
  do:
    runs-on: ubuntu-20.04
    env:
      TEMP_DIR: _tmp_dir
      CONVERTED_PY_FILES: 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install jupytext
        python -m pip install pylint
    - name: Convert committed .ipynb files to .py
      run: |
        echo $GITHUB_ENV
        mkdir ${{env.TEMP_DIR}}

        COMMITTED_IPYNBS=`git diff-tree --no-commit-id --name-only -r --diff-filter=ACM ${{github.sha}}`
        
        while read -r IPYNB_FILE; do
          if [[ "${IPYNB_FILE}" != *.ipynb ]]
          then
            continue
          fi
          PY_FILE=${{env.TEMP_DIR}}/${IPYNB_FILE//.ipynb/.py}
          echo Convert "${IPYNB_FILE}" to "${PY_FILE}"
          jupytext "${IPYNB_FILE}" -o "${PY_FILE}"
          TMP_FILES="${TMP_FILES}${PY_FILE}"$'\n'
        done <<< "${COMMITTED_IPYNBS}"

        echo "CONVERTED_PY_FILES<<EOF" >> $GITHUB_ENV
        echo "${TMP_FILES}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Lint each converted .py files
      run: |
        while read -r PY_FILE; do
          if [ ! -z "${PY_FILE}" ]
          then
            # --exit-zero argument for preventing to stop this step.
            pylint --exit-zero "${PY_FILE}"
          fi
        done <<< "${{env.CONVERTED_PY_FILES}}"
