name: jupytext

on: [push]

jobs:
  do:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install jupytext
        pip install pylint
    - name: Convert committed .ipynb files to .py
      run: |
        TEMP_DIR=tmp_dir
        mkdir ${TEMP_DIR}
        COMMITTED_IPYNBS=`git ls-files "*.ipynb" --with-tree=${{github.sha}}`
        echo ${COMMITTED_IPYNBS} | while read p; do
          PY_FILE=${TEMP_DIR}/${p//.ipynb/.py}
          echo Convert ${p} to ${PY_FILE}
          jupytext ${p} -o ${PY_FILE}
          pylint ${PY_FILE}
        done
        ls -hltr
        ls -hltr ${TEMP_DIR}
      continue-on-error: true
    - name: ENV var test
      run: |
        echo $TEMP_DIR
        echo $PY_FILE