name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "12.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
      continue-on-error: false
  after_build:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: do something after build
      run: |
        echo "HELLO!"
        echo `ls -al`
  parallel_build:
    runs-on: ubuntu-latest
    steps:
    - name: tmp
      run: |
        ls -ltr
        pwd
    - uses: actions/checkout@v3
    - name: do something
      run: |
        git ls-files
    - name: set git config
      run: |
        git config --list
        git config --local user.name "${{github.actor}}123456"
        git config --local user.email "${{github.actor}}@users.noreply.github.com"
        git config --list
    - name: get files
      run: |
        ls -hltr
        ls -hltr *
        pwd
    - name: commit a file
      run: |
        echo "This message from git actions.\n" >> msg.txt
        git add msg.txt
        git commit -m "commit from git actions"
        git push
